version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: borderless-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: borderless
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - borderless-network

networks:
  borderless-network:
    driver: bridge

volumes:
  postgres_data:
    driver: bridge
