version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: template-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - template-network

networks:
  template-network:
    driver: bridge

volumes:
  postgres_data: 
    driver: bridge