version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: borderless-postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - borderless-network

networks:
  borderless-network:
    driver: bridge

volumes:
  postgres_data: 
    driver: bridge